// data.js

// --- AUTH DATA (New Structure) ---
const CREDENTIALS = {
  Ankit: "12345",
  Anshul: "123",
  Jio: "789",
  YaminArora: "YaminA008!",
  Dhruvv: "Upsc@1234",
};

// --- TEST SERIES DATABASE ---
const testSeriesDatabase = {
  "next-ias": {
    title: "Next IAS Prelims 2026 Test Series",
    description: "Download latest tests with solutions",
    tests: [
      {
        id: 18,
        date: "24th Dec 2025",
        title: "NEXT IAS Prelims 2026 Test 18",
        link: "NEXT-IAS-Prelims-2026-Test-18-With-Question-and-answers .pdf",
      },
      {
        id: 17,
        date: "8th Dec 2025",
        title: "NEXT IAS Prelims 2026 Test 17",
        link: "NEXT-IAS-Prelims-2026-Test-17-With-Question-and-answers .pdf",
      },
      {
        id: 16,
        date: "5th Dec 2025",
        title: "NEXT IAS Prelims 2026 Test 16",
        link: "NEXT-IAS-Prelims-2026-Test-16-With-Question-and-answers .pdf",
      },
      {
        id: 14,
        date: "12th Nov 2025",
        title: "NEXT IAS Prelims 2026 Test 14",
        link: "NEXT-IAS-Prelims-2026-Test-14-With-Question-and-answers .pdf",
      },
      {
        id: 13,
        date: "12th Nov 2025",
        title: "NEXT IAS Prelims 2026 Test 13",
        link: "NEXT-IAS-Prelims-2026-Test-13-With-Question-and-answers .pdf",
      },
      {
        id: 12,
        date: "11th Nov 2025",
        title: "NEXT IAS Prelims 2026 Test 12",
        link: "NEXT-IAS-Prelims-2026-Test-12-With-Question-and-answers .pdf",
      },
      {
        id: 11,
        date: "11th Nov 2025",
        title: "NEXT IAS Prelims 2026 Test 11",
        link: "NEXT-IAS-Prelims-2026-Test-11-With-Question-and-answers .pdf",
      },
      {
        id: 10,
        date: "11th Nov 2025",
        title: "NEXT IAS Prelims 2026 Test 10",
        link: "NEXT-IAS-Prelims-2026-Test-10-With-Question-and-answers .pdf",
      },
      {
        id: 9,
        date: "11th Nov 2025",
        title: "NEXT IAS Prelims 2026 Test 9",
        link: "NEXT-IAS-Prelims-2026-Test-9-With-Question-and-answers .pdf",
      },
      {
        id: 8,
        date: "10th Nov 2025",
        title: "NEXT IAS Prelims 2026 Test 8",
        link: "NEXT-IAS-Prelims-2026-Test-8-With-Question-and-answers .pdf",
      },
      {
        id: 7,
        date: "10th Nov 2025",
        title: "NEXT IAS Prelims 2026 Test 7",
        link: "NEXT-IAS-Prelims-2026-Test-7-With-Question-and-answers .pdf",
      },
      {
        id: 6,
        date: "10th Nov 2025",
        title: "NEXT IAS Prelims 2026 Test 6",
        link: "NEXT-IAS-Prelims-2026-Test-6-With-Question-and-answers .pdf",
      },
      {
        id: 5,
        date: "10th Nov 2025",
        title: "NEXT IAS Prelims 2026 Test 5",
        link: "NEXT-IAS-Prelims-2026-Test-5-With-Question-and-answers .pdf",
      },
      {
        id: 4,
        date: "10th Nov 2025",
        title: "NEXT IAS Prelims 2026 Test 4",
        link: "NEXT-IAS-Prelims-2026-Test-4-With-Question-and-answers .pdf",
      },
      {
        id: 3,
        date: "10th Nov 2025",
        title: "NEXT IAS Prelims 2026 Test 3",
        link: "NEXT-IAS-Prelims-2026-Test-3-With-Question-and-answers .pdf",
      },
      {
        id: 2,
        date: "6th Nov 2025",
        title: "NEXT IAS Prelims 2026 Test 2",
        link: "NEXT-IAS-Prelims-2026-Test-2-With-Question-and-answers .pdf",
      },
      {
        id: 1,
        date: "14th Nov 2025",
        title: "NEXT IAS Prelims 2026 Test 1",
        link: "NEXT-IAS-Prelims-2026-Test-1-With-Question-and-answers .pdf",
      },
    ],
  },
  "gs-score": {
    title: "GS Score Prelims 2026 Test Series",
    description: "All India Open Mock Tests & Polity Modular Tests",
    tests: [
      {
        id: "Open 7",
        date: "21st Nov 2025",
        title: "GS Score Prelims 2026 All India Open Mock Test 7",
        link: "GS-Score-Prelims-2026-All-India-Open-Mock-Test-7-Download-Pdf.pdf",
      },
      {
        id: "Open 6",
        date: "21st Nov 2025",
        title: "GS Score Prelims 2026 All India Open Mock Test 6",
        link: "GS-Score-Prelims-2026-All-India-Open-Mock-Test-6-Download-Pdf.pdf",
      },
      {
        id: "Open 5",
        date: "21st Nov 2025",
        title: "GS Score Prelims 2026 All India Open Mock Test 5",
        link: "GS-Score-Prelims-2026-All-India-Open-Mock-Test-5-Download-Pdf.pdf",
      },
      {
        id: "Open 3",
        date: "19th Nov 2025",
        title: "GS Score Prelims 2026 All India Open Mock Test 3",
        link: "GS-Score-Prelims-2026-All-India-Open-Mock-Test-3-Download-Pdf.pdf",
      },
      {
        id: "Open 2",
        date: "19th Nov 2025",
        title: "GS Score Prelims 2026 All India Open Mock Test 2",
        link: "GS-Score-Prelims-2026-All-India-Open-Mock-Test-2-Download-Pdf.pdf",
      },
      {
        id: "Open 1",
        date: "19th Nov 2025",
        title: "GS Score Prelims 2026 All India Open Mock Test 1",
        link: "GS-Score-Prelims-2026-All-India-Open-Mock-Test-1-Download-Pdf.pdf",
      },
      {
        id: "Polity 5",
        date: "30th Oct 2025",
        title: "GS SCORE Prelims 2026 Polity Test 5 With Solution",
        link: "gs-score-prelims-2026-polity-test-5-with-solution-download-pdf.pdf",
      },
      {
        id: "Polity 4",
        date: "30th Oct 2025",
        title: "GS SCORE Prelims 2026 Polity Test 4 With Solution",
        link: "gs-score-prelims-2026-polity-test-4-with-solution-download-pdf.pdf",
      },
      {
        id: "Polity 3",
        date: "30th Oct 2025",
        title: "GS SCORE Prelims 2026 Polity Test 3 With Solution",
        link: "gs-score-prelims-2026-polity-test-3-with-solution-download-pdf.pdf",
      },
      {
        id: "Polity 2",
        date: "30th Oct 2025",
        title: "GS SCORE Prelims 2026 Polity Test 2 With Solution",
        link: "gs-score-prelims-2026-polity-test-2-with-solution-download-pdf.pdf",
      },
      {
        id: "Polity 1",
        date: "30th Oct 2025",
        title: "GS SCORE Prelims 2026 Polity Test 1 With Solution",
        link: "gs-score-prelims-2026-polity-test-1-with-solution-download-pdf.pdf",
      },
    ],
  },
  "vision-ias": {
    title: "Vision IAS Prelims 2026 Test Series",
    description: "Comprehensive Test Series (General Studies & CSAT)",
    tests: [
      {
        id: "18",
        date: "20th Dec 2025",
        title: "Vision IAS Prelims 2026 Test 18 in English With Solution",
        author: "Admin",
        link: "vision-ias-prelims-2026-test-18-with-solution-in-english-and-hindi-pdf.pdf",
      },
      {
        id: "17",
        date: "20th Dec 2025",
        title: "Vision IAS Prelims 2026 Test 17 in English With Solution",
        author: "Admin",
        link: "vision-ias-prelims-2026-test-17-with-solution-in-english-and-hindi-pdf.pdf",
      },
      {
        id: "CSAT 3",
        date: "20th Dec 2025",
        title: "VISION IAS Prelims 2026 CSAT Test 3 With Solution in English",
        author: "Admin",
        link: "vision-ias-prelims-2026-csat-test-3-with-solution-in-english-and-hindi-pdf.pdf",
      },
      {
        id: "16",
        date: "8th Dec 2025",
        title: "Vision IAS Prelims 2026 Test 16 in English With Solutions",
        author: "Admin",
        link: "vision-ias-prelims-2026-test-16-with-solution-in-english-and-hindi-pdf.pdf",
      },
      {
        id: "14",
        date: "8th Dec 2025",
        title: "Vision IAS Prelims 2026 Test 14 in English With Solutions",
        author: "Admin",
        link: "vision-ias-prelims-2026-test-14-with-solution-in-english-and-hindi-pdf.pdf",
      },
      {
        id: "13",
        date: "3rd Dec 2025",
        title: "Vision IAS Prelims 2026 Test 13 in English With Solutions",
        author: "Admin",
        link: "vision-ias-prelims-2026-test-13-with-solution-in-english-and-hindi-pdf.pdf",
      },
      {
        id: "12",
        date: "3rd Dec 2025",
        title: "Vision IAS Prelims 2026 Test 12 in English With Solutions",
        author: "Admin",
        link: "vision-ias-prelims-2026-test-12-with-solution-in-english-and-hindi-pdf.pdf",
      },
      {
        id: "11",
        date: "3rd Nov 2025",
        title: "Vision IAS Prelims 2026 Test 11 in English With Solutions",
        author: "Admin",
        link: "vision-ias-prelims-2026-test-11-with-solution-in-english-and-hindi-pdf.pdf",
      },
      {
        id: "10",
        date: "3rd Nov 2025",
        title: "Vision IAS Prelims 2026 Test 10 With Solutions in English",
        author: "Admin",
        link: "vision-ias-prelims-2026-test-10-with-solution-in-english-and-hindi-pdf.pdf",
      },
      {
        id: "9",
        date: "29th Oct 2025",
        title: "Vision IAS Prelims 2026 Test 9 With Solution in English",
        author: "Vivekananda",
        link: "vision-ias-prelims-2026-test-9-with-solution-in-english-and-hindi-pdf.pdf",
      },
      {
        id: "8",
        date: "29th Oct 2025",
        title: "Vision IAS Prelims 2026 Test 8 With Solution in English",
        author: "Vivekananda",
        link: "vision-ias-prelims-2026-test-8-with-solution-in-english-and-hindi-pdf.pdf",
      },
      {
        id: "7",
        date: "29th Oct 2025",
        title: "Vision IAS Prelims 2026 Test 7 With Solution in English",
        author: "Vivekananda",
        link: "vision-ias-prelims-2026-test-7-with-solution-in-english-and-hindi-pdf.pdf",
      },
      {
        id: "6",
        date: "28th Oct 2025",
        title: "Vision IAS Prelims 2026 Test 6 With Solution in English",
        author: "Vivekananda",
        link: "vision-ias-prelims-2026-test-6-with-solution-in-english-and-hindi-pdf.pdf",
      },
      {
        id: "5",
        date: "26th Aug 2025",
        title: "Vision IAS Prelims 2026 Test 5 With Solution in English",
        author: "Admin",
        link: "vision-ias-prelims-2026-test-5-with-solution-in-english-and-hindi-pdf.pdf",
      },
      {
        id: "4",
        date: "26th Aug 2025",
        title: "Vision IAS Prelims 2026 Test 4 With Solution in English",
        author: "Admin",
        link: "vision-ias-prelims-2026-test-4-with-solution-in-english-and-hindi-pdf.pdf",
      },
      {
        id: "3",
        date: "25th Aug 2025",
        title: "Vision IAS Prelims 2026 Test 3 With Solution in English",
        author: "Admin",
        link: "vision-ias-prelims-2026-test-3-with-solution-in-english-and-hindi-pdf.pdf",
      },
      {
        id: "2",
        date: "17th July 2025",
        title: "Vision IAS Prelims 2026 Test 2 With Solution in English",
        author: "Admin",
        link: "vision-ias-prelims-2026-test-2-with-solution-in-english-and-hindi-pdf.pdf",
      },
      {
        id: "1",
        date: "17th July 2025",
        title: "Vision IAS Prelims 2026 Test 1 With Solution in English",
        author: "Admin",
        link: "vision-ias-prelims-2026-test-1-with-solution-in-english-and-hindi-pdf.pdf",
      },
    ],
  },
};
